//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAttendece.ADODBFIle
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminLogin
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> MobileNumber { get; set; }
        public string RoleId { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string UserPassword { get; set; }
    }
}
