//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAttendece.ADODBFIle
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendence_Master
    {
        public int Attendence_Id { get; set; }
        public Nullable<System.DateTime> Attendence_Date { get; set; }
        public Nullable<System.DateTime> Cheack_In_Time { get; set; }
        public Nullable<System.DateTime> Cheack_Out_Time { get; set; }
        public Nullable<int> EMP_Id { get; set; }
    }
}
