//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAttendece.ADODBFIle
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Master
    {
        public int EMP_Id { get; set; }
        public string EMP_Name { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public Nullable<int> Office_Id { get; set; }
    }
}
