//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAttendece.ADODBFIle
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday_Master
    {
        public int Holiday_Id { get; set; }
        public string Holiday_Name { get; set; }
        public Nullable<System.DateTime> Holiday_Date { get; set; }
    }
}
