//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAttendece.ADODBFIle
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office_Master
    {
        public int Office_Id { get; set; }
        public string Office_Name { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> Cantact_Info { get; set; }
    }
}
