//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAttendece.ADODBFIle
{
    using System;
    using System.Collections.Generic;
    
    public partial class Working_day_Master
    {
        public int Working_Day_Id { get; set; }
        public string Day_Of_Week { get; set; }
        public Nullable<System.DateTime> Start_Time { get; set; }
        public Nullable<System.DateTime> End_Time { get; set; }
    
        public virtual Working_day_Master Working_day_Master1 { get; set; }
        public virtual Working_day_Master Working_day_Master2 { get; set; }
    }
}
